export const metadata = {
  title: 'Create Next App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="mdl-js"
    >
      <body>
        <header
          style={
            {
              backgroundColor: 'lightblue',
              position: 'fixed', top: '0', width: '100%'
            }
          }>
          <h1>Header</h1>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'lightblue',
            position: 'fixed', bottom: '0', width: '100%'
          }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
