export const metadata = {
    title: 'About Page',
    description: 'Generated by Next.js',
}
export default function AboutPage() {
    return (
        <div>
            <h1>AboutPage</h1>
        </div>
    );
}