
import CounterPage from "./counter";
import { useState } from "react";

export const metadata = {
    title: 'Counter Page',
    description: 'Generated by Next.js',
}
export default function Counter() {
    return (
        <div>
            <CounterPage />
        </div>
    );
}